### PR TITLE
Skins

### PR DESCRIPTION
**Pull request by NullStuff**
Added a variety of locations to get skins for Steam Deck, including custom making your own skins!

### CODE REVIEW

**Comment by mikeroyal** [comment]
Both PRs for Cases and Skins have conflicts. If you can't resovle them I recommend combining both into one PR.

**Comment by NullStuff** [comment]
Both conflicts have been resolved, but I think merging either one will cause a conflict with the other since they both edit the lines above the JSAUX Dock.

**Comment by mikeroyal** [comment]
Yeah, that was the issue. Well your PR for Cases went through just resolve this Skins PR one more time and I'll push it through.

**Comment by NullStuff** [comment]
I believe I fixed it correctly. Great project by the way, I really like it.

**Comment by mikeroyal** [comment]
Looks good! Thank you for your contributions!

**Pull request merged**
